### ISSUE TITLE
Can't see the video but can hear the voice

### ISSUE THREAD

**Issue by TingtingG233** [mfkl/LibVLCSharp.Forms.WPF.Test#1]
Hi,

I  have import LibVLCSharp ，and it is wonderful on my windows 10 os. But when I run the same app on my win10 Tablet and win7 os, I can't see the video but can hear the voice. I don't know why. 
Could you please help me?

Best Regards,
Tingting

**Comment by mfkl** [comment]
This is the wrong repository, try on gitlab but we gonna need a lot more info (see issue template).
